{  
   "result":[  
      {  
         "id":"1",
         "name":"belal",
         "email":"belal@mail.com"
      },
      {  
         "id":"3",
         "name":"sunny",
         "email":"sunny@mail.com"
      },
      {  
         "id":"4",
         "name":"belal",
         "email":"belal@gmail.com"
      },
      {  
         "id":"5",
         "name":"test1",
         "email":"ashwinpatil19@gmail.com"
      }
   ]
}